@UserManagementAPI_HostAddress = http://localhost:5226

### Get all users
GET {{UserManagementAPI_HostAddress}}/api/users
Accept: application/json
Authorization: Bearer mysecrettoken

### Get user by ID
GET {{UserManagementAPI_HostAddress}}/api/users/1
Accept: application/json
Authorization: Bearer mysecrettoken

### Create a new user
POST {{UserManagementAPI_HostAddress}}/api/users
Content-Type: application/json
Authorization: Bearer mysecrettoken

{
  "firstName": "Charlie",
  "lastName": "Pham",
  "email": "charlieww211@company.com",
  "phoneNumber": "555123456",
  "department": "IT",
  "role": "Support Engineer"
}

### Update an existing user
PUT {{UserManagementAPI_HostAddress}}/api/users/1
Content-Type: application/json
Authorization: Bearer mysecrettoken

{
  "firstName": "Alice",
  "lastName": "Ho",
  "email": "alice.updated@company.com",
  "phoneNumber": "111222333",
  "department": "HR",
  "role": "Senior Manager"
}

### Delete a user
DELETE {{UserManagementAPI_HostAddress}}/api/users/2
Authorization: Bearer mysecrettoken